name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      GECKODRIVER_VERSION: "0.31.0"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Initialize BuildKit and Register arm64 and armv7
      run: |
        docker buildx use `docker buildx create`
        docker run --rm --privileged aptman/qus -- -r
        docker run --rm --privileged aptman/qus -s -- -p
    - name: Build the Docker image build environments for each architecture
      run: |
        docker buildx build --load --platform linux/arm/v7 -t local/geckodriver-armv7-builder .
        docker buildx build --load --platform linux/arm64 -t local/geckodriver-arm64-builder .
    - name: Build the geckodriver binaries in the artifacts directory
      run: |
        docker run --rm --platform linux/arm/v7 -v $PWD/artifacts/armv7:/media/host -w /opt/geckodriver --name geckodriver-armv7-builder local/geckodriver-armv7-builder
        docker run --rm --platform linux/arm64 -v $PWD/artifacts/arm64:/media/host -w /opt/geckodriver --name geckodriver-arm64-builder local/geckodriver-arm64-builder
    - name: Package up the binaries in a tar.gz and calculate md5 hashes
      run: |
        mv artifacts/armv7/geckodriver geckodriver
        tar cvfz geckodriver-v$GECKODRIVER_VERSION-linux-armv7l.tar.gz geckodriver
        md5sum geckodriver-v$GECKODRIVER_VERSION-linux-armv7l.tar.gz > geckodriver-v$GECKODRIVER_VERSION-linux-armv7l.tar.gz.md5
        rm geckodriver
        mv artifacts/arm64/geckodriver geckodriver
        tar cvfz geckodriver-v$GECKODRIVER_VERSION-linux-aarch64.tar.gz geckodriver
        md5sum geckodriver-v$GECKODRIVER_VERSION-linux-aarch64.tar.gz > geckodriver-v$GECKODRIVER_VERSION-linux-aarch64.tar.gz.md5
    - name: Generate release notes
      run: |
        echo "NOTE:  This is an unofficial arm64 build and armhf of geckodriver v$GECKODRIVER_VERSION.  These binaries are compiled and built independently and are not provided by Mozilla." > release_notes.md  
        echo "" >> release_notes.md
        echo "For details of what is contained in this release, see the [official geckodriver release notes](https://github.com/mozilla/geckodriver/releases)." >> release_notes.md
    - name: Publish releases with binaries and md5 hashes
      run: |
        export RELEASE_TAG=$GECKODRIVER_VERSION
        go install github.com/github-release/github-release@v0.10.0
        github-release release --tag $RELEASE_TAG --name $RELEASE_TAG --description "`cat release_notes.md`"
        github-release upload --tag $RELEASE_TAG --file geckodriver-v$GECKODRIVER_VERSION-linux-aarch64.tar.gz
        github-release upload --tag $RELEASE_TAG --file geckodriver-v$GECKODRIVER_VERSION-linux-aarch64.tar.gz.md5
        github-release upload --tag $RELEASE_TAG --file geckodriver-v$GECKODRIVER_VERSION-linux-armv7l.tar.gz
        github-release upload --tag $RELEASE_TAG --file geckodriver-v$GECKODRIVER_VERSION-linux-armv7l.tar.gz.md5
