name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        arch: [armv7l, aarch64]
    env:
      GECKODRIVER_VERSION: "0.31.0"
      ARCH: ${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Initialize BuildKit and Register arm architectures
      run: |
        docker buildx use `docker buildx create`
        docker run --rm --privileged aptman/qus -- -r
        docker run --rm --privileged aptman/qus -s -- -p
        if [ "$ARCH" == "armv7l" ]; then
            echo "PLATFORM=linux/arm/v7" >> $GITHUB_ENV
        elif [ "${{ matrix.arch }}" == "aarch64" ]; then
            echo "PLATFORM=linux/arm64" >> $GITHUB_ENV
        fi
#    - name: Build the Docker image build environment
#      run: |
#        docker buildx build --load --platform $PLATFORM --build-arg GECKODRIVER_VERSION=$GECKODRIVER_VERSION -t local/geckodriver-arm-builder .
#    - name: Build the geckodriver binaries in the artifacts directory
#      run: |
#        docker run --rm --platform $PLATFORM -v $PWD/artifacts:/media/host -w /opt/geckodriver --name geckodriver-arm-builder local/geckodriver-arm-builder
    - name: Package up the binaries in a tar.gz and calculate md5 hashes
      run: |
        echo $ARCH
        wget https://github.com/jamesmortensen/geckodriver-arm-binaries/releases/download/v0.30.0/geckodriver-v0.30.0-linux-aarch64.tar.gz
        wget https://github.com/jamesmortensen/geckodriver-arm-binaries/releases/download/v0.30.0/geckodriver-v0.30.0-linux-armv7l.tar.gz
        mkdir artifacts
        sudo chown -R runner:runner artifacts
        tar xvfz geckodriver-v0.30.0-linux-aarch64.tar.gz
        mv geckodriver artifacts/
        mv artifacts/geckodriver geckodriver
        tar cvfz geckodriver-v$GECKODRIVER_VERSION-linux-$ARCH.tar.gz geckodriver
        md5sum geckodriver-v$GECKODRIVER_VERSION-linux-${{ matrix.arch }}.tar.gz > geckodriver-v$GECKODRIVER_VERSION-linux-${{ matrix.arch }}.tar.gz.md5
    - name: Generate release notes
      run: |
        echo "NOTE:  This is an unofficial arm64 build and armhf of geckodriver v$GECKODRIVER_VERSION.  These binaries are compiled and built independently and are not provided by Mozilla." > release_notes.md  
        echo "" >> release_notes.md
        echo "For details of what is contained in this release, see the [official geckodriver release notes](https://github.com/mozilla/geckodriver/releases)." >> release_notes.md
    - name: Publish releases with binaries and md5 hashes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export RELEASE_TAG=$GECKODRIVER_VERSION
        go install github.com/github-release/github-release@v0.10.0
        VERSION=`~/go/bin/github-release info -u jamesmortensen -r geckodriver-arm-binaries | grep $GECKODRIVER_VERSION | head -n 1 | awk '{print $2}'`
        # Let faster job set the release notes
        if [ "$VERSION" != "v$GECKODRIVER_VERSION" ]; then
            echo "Set release notes"
            ~/go/bin/github-release release -u jamesmortensen -r geckodriver-arm-binaries --tag $RELEASE_TAG --name $RELEASE_TAG --description "`cat release_notes.md`"
        fi
        echo "Upload files..."
        ~/go/bin/github-release upload -u jamesmortensen -r geckodriver-arm-binaries --tag $RELEASE_TAG --file geckodriver-v$GECKODRIVER_VERSION-linux-${{ matrix.arch }}.tar.gz
        ~/go/bin/github-release upload -u jamesmortensen -r geckodriver-arm-binaries --tag $RELEASE_TAG --file geckodriver-v$GECKODRIVER_VERSION-linux-${{ matrix.arch }}.tar.gz.md5
